global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8085']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8083']

  - job_name: 'hotel-service'
    static_configs:
      - targets: ['hotel-service:8081']

  - job_name: 'notification-svc'
    static_configs:
      - targets: ['notification-svc:8080']
